### ISSUE TITLE
The `Create Account` operation contains all the parameters in the input record type as optionl

### ISSUE THREAD

**Issue by sachinira** [ballerina-platform/module-ballerinax-netsuite#20]
**Description:**
In the `Create Account` operation the record type parameter used to represent a new account contains all the fields as optional.
**Operation**
https://github.com/ballerina-platform/module-ballerinax-netsuite/blob/master/netsuite/client.bal#L109

**Types**
https://github.com/ballerina-platform/module-ballerinax-netsuite/blob/master/netsuite/accountTypes.bal#L79
https://github.com/ballerina-platform/module-ballerinax-netsuite/blob/master/netsuite/accountTypes.bal#L108

**Suggested Assignees:**
@SanduDS 

**Affected Product Version:**
Netsuite Connector Version 0.9.6

**OS, DB, other environment details and versions:**    
JDK 11
Ballerina SL Alpha 5
Ubuntu 20.04

**Comment by abeykoon** [comment]
Now we have three types of Accounts. 

1. `Account `
2. `NewAccount `
3. `AccountCommon `

As we have defined three separate record types, required fields for each type is made mandatory as appropriate. Hence issue is addressed.
