### ISSUE TITLE
Token based authentication support

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/module-ballerinax-netsuite#6]
**Description:**
The initial implementation is done based on OAuth 2.0 authentication support. But the refresh token expires 7 days. We need to test whether this limitation(after 7 days, you need to obtain a new refresh token) only occurs in the sandbox environment. If not we need to add token-based authentication support in addition to OAuth 2.0

**Affected Product Version:**
0.9.1

**Comment by SanduDS** [comment]
TBA supports provided with #10

**Comment by abeykoon** [comment]
After revamp, we support SOAP functionality exposed by Netsuite. There, we use `Token Based Authentication`. Issue is not valid anymore.
