### ISSUE TITLE
Netsuite Rest API Beta Changes - NonInventoryItem record type

### ISSUE THREAD

**Issue by Dhanushkas** [ballerina-platform/module-ballerinax-netsuite#8]
**Description:**
NonInventoryItem record type has been removed. Therefore, /nonInventoryItem record path is no longer valid. The API has been updated to new 3 record types called NonInventorySaleItem, NonInventoryResaleItme, NonInventoryPurchaseItem.

**Affected Product Version:**
0.9.1

**Steps to reproduce:**
Run test SalesOrder

**Comment by abeykoon** [comment]
Closed as we moved from REST based implementation.
